const citiesToTimeZoneMap = {
  "Africa/Abidjan": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Accra": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Addis_Ababa": "(GMT+3:00) Nairobi",
  "Africa/Algiers": "(GMT+1:00) West Central Africa",
  "Africa/Asmara": "(GMT+3:00) Kuwait, Riyadh",
  "Africa/Bamako": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Bangui": "(GMT+1:00) West Central Africa",
  "Africa/Banjul": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Bissau": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Blantyre": "(GMT+2:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "Africa/Brazzaville": "(GMT+1:00) West Central Africa",
  "Africa/Bujumbura": "(GMT+2:00) Harare, Pretoria",
  "Africa/Cairo": "(GMT+2:00) Cairo",
  "Africa/Casablanca": "(GMT+1:00) Lisbon",
  "Africa/Conakry": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Dakar": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Dar_es_Salaam": "(GMT+3:00) Nairobi",
  "Africa/Djibouti": "(GMT+3:00) Nairobi",
  "Africa/Douala": "(GMT+1:00) West Central Africa",
  "Africa/El_Aaiun": "(GMT+1:00) Lisbon",
  "Africa/Freetown": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Gaborone": "(GMT+2:00) Harare, Pretoria",
  "Africa/Harare": "(GMT+2:00) Harare, Pretoria",
  "Africa/Johannesburg": "(GMT+2:00) Harare, Pretoria",
  "Africa/Juba": "(GMT+3:00) Nairobi",
  "Africa/Kampala": "(GMT+3:00) Nairobi",
  "Africa/Khartoum": "(GMT+2:00) Cairo",
  "Africa/Kigali": "(GMT+2:00) Harare, Pretoria",
  "Africa/Kinshasa": "(GMT+1:00) West Central Africa",
  "Africa/Lagos": "(GMT-1:00) Cape Verde Islands",
  "Africa/Libreville": "(GMT-1:00) Cape Verde Islands",
  "Africa/Lome": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Luanda": "(GMT-1:00) Cape Verde Islands",
  "Africa/Lubumbashi": "(GMT+2:00) Harare, Pretoria",
  "Africa/Lusaka": "(GMT+2:00) Harare, Pretoria",
  "Africa/Malabo": "(GMT+1:00) West Central Africa",
  "Africa/Maputo": "(GMT+2:00) Harare, Pretoria",
  "Africa/Maseru": "(GMT+2:00) Harare, Pretoria",
  "Africa/Mbabane": "(GMT+2:00) Harare, Pretoria",
  "Africa/Mogadishu": "(GMT+3:00) Nairobi",
  "Africa/Monrovia": "(GMT-10:00) Hawaii",
  "Africa/Nairobi": "(GMT+3:00) Nairobi",
  "Africa/Ndjamena": "(GMT+1:00) West Central Africa",
  "Africa/Niamey": "(GMT+1:00) West Central Africa",
  "Africa/Nouakchott": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Ouagadougou": "(GMT+0:00) Casablanca, Monrovia",
  "Africa/Porto-Novo": "(GMT-1:00) Cape Verde Islands",
  "Africa/Tripoli": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
  "Africa/Tunis": "(GMT+1:00) West Central Africa",
  "Africa/Windhoek": "(GMT-1:00) Cape Verde Islands",
  "America/Anchorage": "(GMT-8:00) Alaska",
  "America/Araguaina": "(GMT-3:00) Brasilia",
  "America/Argentina": "(GMT-3:00) Buenos Aires, Georgetown",
  "America/Asuncion": "(GMT-4:00) Caracas, La Paz",
  "America/Atikokan": "(GMT-5:00) Central Time",
  "America/Bahia": "(GMT-3:00) Brasilia",
  "America/Belem": "(GMT-3:00) Brasilia",
  "America/Belize": "(GMT-6:00) Central America",
  "America/Blanc-Sablon": "(GMT-4:00) Caracas, La Paz",
  "America/Boa_Vista": "(GMT-4:00) Caracas, La Paz",
  "America/Bogota": "(GMT-5:00) Bogota, Lima, Quito",
  "America/Boise": "(GMT-6:00) Mountain Time",
  "America/Cambridge_Bay": "(GMT-6:00) Saskatchewan",
  "America/Campo_Grande": "(GMT-4:00) Caracas, La Paz",
  "America/Cancun": "(GMT-5:00) Guadalajara, Mexico City, Monterrey",
  "America/Caracas": "(GMT-4:00) Caracas, La Paz",
  "America/Cayenne": "(GMT-3:00) Brasilia",
  "America/Chicago": "(GMT-5:00) Central Time",
  "America/Chihuahua": "(GMT-6:00) Chihuahua, La Paz, Mazatlan",
  "America/Coral_Harbour": "(GMT-5:00) Central Time",
  "America/Costa_Rica": "(GMT-6:00) Central America",
  "America/Creston": "(GMT-7:00) Pacific Time",
  "America/Cuiaba": "(GMT-4:00) Caracas, La Paz",
  "America/Danmarkshavn": "(GMT+0:00) Azores",
  "America/Dawson_Creek": "(GMT-7:00) Pacific Time",
  "America/Denver": "(GMT-6:00) Saskatchewan",
  "America/Detroit": "(GMT-4:00) Eastern Time",
  "America/Edmonton": "(GMT-6:00) Central America",
  "America/Eirunepe": "(GMT-5:00) Bogota, Lima, Quito",
  "America/El_Salvador": "(GMT-6:00) Central America",
  "America/Fortaleza": "(GMT-3:00) Brasilia",
  "America/Glace_Bay": "(GMT-3:00) Santiago",
  "America/Godthab": "(GMT-2:00) Greenland",
  "America/Goose_Bay": "(GMT-3:00) Brasilia",
  "America/Guatemala": "(GMT-6:00) Central America",
  "America/Guayaquil": "(GMT-5:00) Bogota, Lima, Quito",
  "America/Guyana": "(GMT-4:00) Caracas, La Paz",
  "America/Halifax": "(GMT-3:00) Santiago",
  "America/Havana": "(GMT-4:00) Eastern Time",
  "America/Hermosillo": "(GMT-7:00) Tijuana",
  "America/Indiana": "(GMT-4:00) Caracas, La Paz",
  "America/Iqaluit": "(GMT-4:00) Eastern Time",
  "America/Jamaica": "(GMT-5:00) Bogota, Lima, Quito",
  "America/Juneau": "(GMT-8:00) Alaska",
  "America/Kentucky": "(GMT-4:00) Eastern Time",
  "America/La_Paz": "(GMT-4:00) Caracas, La Paz",
  "America/Lima": "(GMT-5:00) Bogota, Lima, Quito",
  "America/Los_Angeles": "(GMT-7:00) Pacific Time",
  "America/Maceio": "(GMT-3:00) Brasilia",
  "America/Managua": "(GMT-6:00) Central America",
  "America/Manaus": "(GMT-4:00) Caracas, La Paz",
  "America/Matamoros": "(GMT-5:00) Guadalajara, Mexico City, Monterrey",
  "America/Mazatlan": "(GMT-6:00) Chihuahua, La Paz, Mazatlan",
  "America/Menominee": "(GMT-5:00) Central Time",
  "America/Merida": "(GMT-5:00) Bogota, Lima, Quito",
  "America/Mexico_City": "(GMT-5:00) Guadalajara, Mexico City, Monterrey",
  "America/Moncton": "(GMT-3:00) Santiago",
  "America/Monterrey": "(GMT-5:00) Guadalajara, Mexico City, Monterrey",
  "America/Montevideo": "(GMT-3:00) Montevideo",
  "America/Montreal": "(GMT-4:00) Eastern Time",
  "America/Nassau": "(GMT-4:00) Caracas, La Paz",
  "America/New_York": "(GMT-4:00) Eastern Time",
  "America/Nome": "(GMT-8:00) Alaska",
  "America/North_Dakota": "(GMT-6:00) Central America",
  "America/Ojinaga": "(GMT-6:00) Chihuahua, La Paz, Mazatlan",
  "America/Panama": "(GMT-5:00) Bogota, Lima, Quito",
  "America/Pangnirtung": "(GMT-4:00) Eastern Time",
  "America/Paramaribo": "(GMT-3:00) Brasilia",
  "America/Phoenix": "(GMT-7:00) Arizona",
  "America/Port-au-Prince": "(GMT-4:00) Caracas, La Paz",
  "America/Port_of_Spain": "(GMT-4:00) Caracas, La Paz",
  "America/Porto_Velho": "(GMT-4:00) Caracas, La Paz",
  "America/Puerto_Rico": "(GMT-4:00) Caracas, La Paz",
  "America/Rankin_Inlet": "(GMT-5:00) Central Time",
  "America/Recife": "(GMT-3:00) Brasilia",
  "America/Regina": "(GMT-6:00) Saskatchewan",
  "America/Resolute": "(GMT-5:00) Central Time",
  "America/Rio_Branco": "(GMT-5:00) Bogota, Lima, Quito",
  "America/Santa_Isabel": "(GMT-7:00) Dawson, Yukon",
  "America/Santarem": "(GMT-3:00) Brasilia",
  "America/Santiago": "(GMT-4:00) Caracas, La Paz",
  "America/Santo_Domingo": "(GMT-4:00) Caracas, La Paz",
  "America/Sao_Paulo": "(GMT-3:00) Brasilia",
  "America/Scoresbysund": "(GMT+0:00) Azores",
  "America/Sitka": "(GMT-8:00) Alaska",
  "America/St_Johns": "(GMT-2:30) Newfoundland and Labrador",
  "America/Tegucigalpa": "(GMT-6:00) Central America",
  "America/Thule": "(GMT-3:00) Brasilia",
  "America/Tijuana": "(GMT-7:00) Tijuana",
  "America/Toronto": "(GMT-4:00) Eastern Time",
  "America/Vancouver": "(GMT-7:00) Pacific Time",
  "America/Whitehorse": "(GMT-7:00) Pacific Time",
  "America/Winnipeg": "(GMT-5:00) Central Time",
  "America/Yakutat": "(GMT-8:00) Alaska",
  "America/Yellowknife": "(GMT-6:00) Saskatchewan",
  "Arctic/Longyearbyen": "(GMT-2:00) Greenland",
  "Asia/Aden": "(GMT+3:00) Nairobi",
  "Asia/Almaty": "(GMT+6:00) Almaty, Novosibirsk",
  "Asia/Amman": "(GMT+3:00) Jerusalem",
  "Asia/Anadyr": "(GMT+12:00) Kamchatka, Marshall Islands",
  "Asia/Aqtau": "(GMT+5:00) Ekaterinburg",
  "Asia/Aqtobe": "(GMT+5:00) Ekaterinburg",
  "Asia/Ashgabat": "(GMT+5:00) Baku, Tbilisi, Yerevan",
  "Asia/Baghdad": "(GMT+3:00) Baghdad",
  "Asia/Baku": "(GMT+4:00) Abu Dhabi, Muscat",
  "Asia/Bangkok": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
  "Asia/Beirut": "(GMT+3:00) Jerusalem",
  "Asia/Bishkek": "(GMT+6:00) Almaty, Novosibirsk",
  "Asia/Brunei": "(GMT+8:00) Kuala Lumpur, Singapore",
  "Asia/Choibalsan": "(GMT+8:00) Irkutsk, Ulaanbaatar",
  "Asia/Chongqing": "(GMT+8:00) Beijing, Chongqing, Hong Kong SAR, Urumqi",
  "Asia/Colombo": "(GMT+5:30) Sri Jayawardenepura",
  "Asia/Damascus": "(GMT+3:00) Jerusalem",
  "Asia/Dhaka": "(GMT+6:00) Astana, Dhaka",
  "Asia/Dili": "(GMT+9:00) Seoul",
  "Asia/Dubai": "(GMT+4:00) Abu Dhabi, Muscat",
  "Asia/Dushanbe": "(GMT+5:00) Islamabad, Karachi, Tashkent",
  "Asia/Harbin": "(GMT+8:00) Beijing, Chongqing, Hong Kong SAR, Urumqi",
  "Asia/Hebron": "(GMT+3:00) Jerusalem",
  "Asia/Ho_Chi_Minh": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
  "Asia/Hong_Kong": "(GMT+8:00) Taipei",
  "Asia/Hovd": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
  "Asia/Irkutsk": "(GMT+8:00) Irkutsk, Ulaanbaatar",
  "Asia/Jakarta": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
  "Asia/Jayapura": "(GMT+9:00) Seoul",
  "Asia/Jerusalem": "(GMT+3:00) Jerusalem",
  "Asia/Kabul": "(GMT+4:30) Kabul",
  "Asia/Kamchatka": "(GMT+12:00) Kamchatka, Marshall Islands",
  "Asia/Karachi": "(GMT+5:00) Islamabad, Karachi, Tashkent",
  "Asia/Kashgar": "(GMT+6:00) Almaty, Novosibirsk",
  "Asia/Kathmandu": "(GMT+5:45) Kathmandu",
  "Asia/Khandyga": "(GMT+9:00) Seoul",
  "Asia/Kolkata": "(GMT+5:30) Chennai, Kolkata, Mumbai, New Delhi",
  "Asia/Krasnoyarsk": "(GMT+7:00) Krasnoyarsk",
  "Asia/Kuala_Lumpur": "(GMT+8:00) Kuala Lumpur, Singapore",
  "Asia/Kuching": "(GMT+8:00) Kuala Lumpur, Singapore",
  "Asia/Kuwait": "(GMT+3:00) Kuwait, Riyadh",
  "Asia/Magadan": "(GMT+11:00) Magadan, Solomon Islands, New Caledonia",
  "Asia/Makassar": "(GMT+8:00) Kuala Lumpur, Singapore",
  "Asia/Manila": "(GMT+8:00) Taipei",
  "Asia/Muscat": "(GMT+4:00) Abu Dhabi, Muscat",
  "Asia/Nicosia": "(GMT+3:00) Jerusalem",
  "Asia/Novokuznetsk": "(GMT+7:00) Krasnoyarsk",
  "Asia/Novosibirsk": "(GMT+7:00) Krasnoyarsk",
  "Asia/Omsk": "(GMT+6:00) Almaty, Novosibirsk",
  "Asia/Oral": "(GMT+5:00) Ekaterinburg",
  "Asia/Phnom_Penh": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
  "Asia/Pontianak": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
  "Asia/Pyongyang": "(GMT+9:00) Seoul",
  "Asia/Qatar": "(GMT+3:00) Kuwait, Riyadh",
  "Asia/Qyzylorda": "(GMT+6:00) Almaty, Novosibirsk",
  "Asia/Rangoon": "(GMT+6:30) Yangon Rangoon",
  "Asia/Riyadh": "(GMT+3:00) Kuwait, Riyadh",
  "Asia/Sakhalin": "(GMT+11:00) Magadan, Solomon Islands, New Caledonia",
  "Asia/Samarkand": "(GMT+5:00) Islamabad, Karachi, Tashkent",
  "Asia/Seoul": "(GMT+9:00) Seoul",
  "Asia/Shanghai": "(GMT+8:00) Beijing, Chongqing, Hong Kong SAR, Urumqi",
  "Asia/Taipei": "(GMT+8:00) Taipei",
  "Asia/Tashkent": "(GMT+5:00) Islamabad, Karachi, Tashkent",
  "Asia/Tbilisi": "(GMT+4:00) Abu Dhabi, Muscat",
  "Asia/Tehran": "(GMT+4:30) Kabul",
  "Asia/Thimphu": "(GMT+6:00) Astana, Dhaka",
  "Asia/Tokyo": "(GMT+9:00) Osaka, Sapporo, Tokyo",
  "Asia/Ulaanbaatar": "(GMT+8:00) Irkutsk, Ulaanbaatar",
  "Asia/Urumqi": "(GMT+6:00) Almaty, Novosibirsk",
  "Asia/Ust-Nera": "(GMT+10:00) Yakutsk",
  "Asia/Vientiane": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
  "Asia/Vladivostok": "(GMT+10:00) Vladivostok",
  "Asia/Yakutsk": "(GMT+10:00) Yakutsk",
  "Asia/Yekaterinburg": "(GMT+5:00) Ekaterinburg",
  "Asia/Yerevan": "(GMT+4:00) Abu Dhabi, Muscat",
  "Atlantic/Canary": "(GMT+1:00) Canary Islands",
  "Atlantic/Reykjavik": "(GMT+0:00) Azores",
  "Atlantic/South_Georgia": "(GMT-2:00) Greenland",
  "Atlantic/Stanley": "(GMT-3:00) Santiago",
  "Australia/Adelaide": "(GMT+9:30) Adelaide",
  "Australia/Brisbane": "(GMT+10:00) Brisbane",
  "Australia/Broken_Hill": "(GMT+9:30) Adelaide",
  "Australia/Darwin": "(GMT+9:30) Darwin",
  "Australia/Hobart": "(GMT+10:00) Hobart",
  "Australia/Melbourne": "(GMT+10:00) Hobart",
  "Australia/Perth": "(GMT+8:00) Perth",
  "Australia/Sydney": "(GMT+10:00) Canberra, Melbourne, Sydney",
  "Europe/Amsterdam": "(GMT+2:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "Europe/Athens": "(GMT+3:00) Athens, Minsk",
  "Europe/Belgrade": "(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  "Europe/Berlin": "(GMT-2:00) Greenland",
  "Europe/Bratislava": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
  "Europe/Brussels": "(GMT+2:00) Brussels, Copenhagen, Madrid, Paris",
  "Europe/Bucharest": "(GMT+3:00) Bucharest",
  "Europe/Budapest": "(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  "Europe/Chisinau": "(GMT+3:00) Bucharest",
  "Europe/Copenhagen": "(GMT-2:00) Greenland",
  "Europe/Dublin": "(GMT+1:00) Dublin",
  "Europe/Helsinki": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
  "Europe/Istanbul": "(GMT+3:00) Bucharest",
  "Europe/Kaliningrad": "(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  "Europe/Kiev": "(GMT+3:00) Bucharest",
  "Europe/Lisbon": "(GMT+1:00) Lisbon",
  "Europe/Ljubljana": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
  "Europe/London": "(GMT+1:00) Edinburgh, London",
  "Europe/Luxembourg": "(GMT+2:00) Brussels, Copenhagen, Madrid, Paris",
  "Europe/Madrid": "(GMT+2:00) Brussels, Copenhagen, Madrid, Paris",
  "Europe/Mariehamn": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
  "Europe/Minsk": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
  "Europe/Moscow": "(GMT+3:00) Istanbul, Moscow, St. Petersburg, Volgograd",
  "Europe/Oslo": "(GMT-2:00) Greenland",
  "Europe/Paris": "(GMT+2:00) Brussels, Copenhagen, Madrid, Paris",
  "Europe/Podgorica": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
  "Europe/Prague": "(GMT-2:00) Greenland",
  "Europe/Riga": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
  "Europe/Rome": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
  "Europe/Samara": "(GMT+4:00) Abu Dhabi, Muscat",
  "Europe/Sarajevo": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
  "Europe/Simferopol": "(GMT+3:00) Bucharest",
  "Europe/Skopje": "(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  "Europe/Sofia": "(GMT+3:00) Bucharest",
  "Europe/Stockholm": "(GMT-2:00) Greenland",
  "Europe/Tallinn": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
  "Europe/Tirane": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
  "Europe/Uzhgorod": "(GMT+3:00) Bucharest",
  "Europe/Vienna": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
  "Europe/Vilnius": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
  "Europe/Volgograd": "(GMT+4:00) Abu Dhabi, Muscat",
  "Europe/Warsaw": "(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  "Europe/Zagreb": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
  "Europe/Zaporozhye": "(GMT+3:00) Istanbul, Moscow, St. Petersburg, Volgograd",
  "Europe/Zurich": "(GMT+2:00) Brussels, Copenhagen, Madrid, Paris",
  "Indian/Antananarivo": "(GMT+3:00) Nairobi",
  "Indian/Kerguelen": "(GMT+5:00) Islamabad, Karachi, Tashkent",
  "Pacific/Auckland": "(GMT+12:00) Fiji Islands",
  "Pacific/Efate": "(GMT+11:00) Magadan, Solomon Islands, New Caledonia",
  "Pacific/Fiji": "(GMT+12:00) Fiji Islands",
  "Pacific/Galapagos": "(GMT-6:00) Central America",
  "Pacific/Guadalcanal": "(GMT-11:00) Midway Island, Samoa",
  "Pacific/Honolulu": "(GMT-10:00) Hawaii",
  "Pacific/Noumea": "(GMT+11:00) Magadan, Solomon Islands, New Caledonia",
  "Pacific/Port_Moresby": "(GMT+10:00) Brisbane",
};
export default citiesToTimeZoneMap;
